#!/bin/bash

date_pattern=`date "+%Y-%m-%d"`-

read -r -p "Post name > "
title=${REPLY}
clean_title=`echo $title | tr "[:upper:]" "[:lower:]"]` #Lower Case
clean_title=`echo $clean_title | tr -dc '[a-z0-9\. -_]'` #Keep spaces and letters
clean_title=`echo $clean_title | tr " " "-"` #Replace spaces by dashes

filename=$date_pattern$clean_title.md
author="Yinyanghu"

cat > "posts/"$filename <<EOF
---
title: $title
author: $author
tags:
---

---

☯ Yinyanghu, 2013

EOF

vim "posts/"$filename
